#ifndef _ENA_CONFIG_H_
#define _ENA_CONFIG_H_
#define ENA_HAVE_PCI_DEV_ID 1
#define ENA_HAVE_XDP_DO_FLUSH 1
#define ENA_HAVE_CPUMASK_LOCAL_SPREAD 1
#define ENA_HAVE_UPDATE_AFFINITY_HINT 1
#endif /* _ENA_CONFIG_H_ */
